// <auto-generated />
using Film_Collection.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Film_Collection.Migrations
{
    [DbContext(typeof(FilmCollectionContext))]
    partial class FilmCollectionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Film_Collection.Models.MoviesModel", b =>
                {
                    b.Property<int>("FormId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lent_To")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("FormId");

                    b.ToTable("Films");

                    b.HasData(
                        new
                        {
                            FormId = 1,
                            Category = "Horror",
                            Director = "James Wan",
                            Edited = false,
                            Lent_To = "Aaron",
                            Rating = "PG-13",
                            Title = "Insidious",
                            Year = 2010
                        },
                        new
                        {
                            FormId = 2,
                            Category = "Sci-fi/Mystery/Thriller",
                            Director = "Christopher Nolan",
                            Edited = false,
                            Notes = "Dreams",
                            Rating = "PG-13",
                            Title = "Inception",
                            Year = 2010
                        },
                        new
                        {
                            FormId = 3,
                            Category = "Animated",
                            Director = "Stephen Sandoval",
                            Edited = false,
                            Rating = "PG",
                            Title = "Tangled",
                            Year = 2010
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
